version: "3.8"

services:
  backend:
    build: ./backend
    container_name: teenz-backend
    ports:
      - "5000:5000" # Backend exposed on port 5000 (internal)
    env_file:
      - backend/.env
    depends_on:
      - db
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    container_name: teenz-frontend
    # ports:
    #   - "80:3000" 
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:15
    container_name: teenz-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432" # Exposed for backend access only
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
